### ISSUE TITLE
Update the BOX

### ISSUE THREAD

**Issue by FDiskas** [acorncom/yii2-advanced-with-vagrant#4]
The ubuntu is outdated
use something like

```
    override.vm.box = "ubuntu/trusty64"
    override.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"
```

**Comment by acorncom** [comment]
Happy to take a pull request on this :-) My acorncom/base_vagrant repo is kept more current, so you could reference that ...

**Comment by FDiskas** [comment]
I can't even start your version.
Its' fails on

```
Initial apt-get update...
```

I got the error

```
==> default: W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/raring-backports/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default: E: Some index files failed to download. They have been ignored, or old ones used instead.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Process finished with exit code 1
```

I'm not an expert on vagrant and linux servers so I cant fix this.

**Comment by acorncom** [comment]
If you can't fix it, then I'd suggest you use the base-vagrant setup instead. That will at least get you a functioning Linux box that can then be used with Yii2

**Comment by FDiskas** [comment]
I tryed https://github.com/iJackUA/try-yii2 and this works very good, but to slow at first startup
